mysite/books/urls.py
from django.conf.urls import url, include

from . import views


urlpatterns = [
    url(r'^$', views.homepage),
    url(r'^search-form/$', views.search_form),
    url(r'^search/$', views.search),
    # url(r'^reviews/2003/$', views.special_case_2003),
    url(r'^(?P<year>[0-9]{4})/$', views.year_archive, name='reviews-year-archive'),
    # url(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/$', views.month_archive),
    # url(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/(?P<day>[0-9]]{2})/$', views.review_detail),
    url(r'^publishers/$', views.PublisherList.as_view()),
]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from . import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^hello/$', views.hello),
    url(r'^time/$', views.current_datetime),
    url(r'^time/plus/(\d{1,2})/$', views.hours_ahead),
    url(r'^meta/$', views.display_meta),
    url(r'^contact/$', views.contact),
    url(r'^reviews/', include('books.urls', namespace='author-reviews'))
]


if settings.DEBUG:
    urlpatterns += [url(r'^debuginfo/$', views.debug),]

mysite/books/models.py
from django.db import models


class Publisher(models.Model):
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=60)
    state_province = models.CharField(max_length=30)
    country = models.CharField(max_length=50)
    website = models.URLField()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-name']


class Author(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=40)
    email = models.EmailField(blank=True, verbose_name='e-mail')

    def __str__(self):
        return u'%s %s' % (self.first_name, self.last_name)


class BookManager(models.Manager):
    def title_count(self, keyword):
        return self.filter(title__icontains=keyword).count()


class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField(Author)
    publisher = models.ForeignKey(Publisher)
    publication_date = models.DateField()
    num_pages = models.IntegerField(blank=True, null=True)
    objects = BookManager()

    def __str__(self):
        return self.title


class Person(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=40)
    birth_date = models.DateField()

mysite/mysite/forms.py
from django import forms


class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    email = forms.EmailField(required=False, label='E-mail')
    message = forms.CharField(widget=forms.Textarea)

    def clean_message(self):
        message = self.cleaned_data['message']
        num_words = len(message.split())
        if num_words < 4:
            raise forms.ValidationError("Not enough word!")
        return message

mysite/books/views.py
from django.shortcuts import render
from django.http import HttpResponse

from .models import Book, Publisher
from django.views.generic import ListView, DetailView


class PublisherDetail(DetailView):
    model = Publisher
    # context_object_name = 'publisher'
    # queryset = Publisher.objects.all()

    def get_context_data(self, **kwargs):
        # call the base implementation first to get a context
        context = super(PublisherDetail, self).get_context_data(**kwargs)
        # add in a queryset of all the books
        context['book_list'] = Book.objects.all()
        return context


class BookList(ListView):
    queryset = Book.objects.order_by('-publication_date')
    context_object_name = 'book_list'


class PublisherList(ListView):
    model = Publisher
    context_object_name = 'my_favorite_publishers'


def homepage(request):
    return render(request, 'homepage.html')


def search_form(request):
    return render(request, 'search_form.html')


def search(request):
    # if 'q' in request.GET
    # other two methods are BAD
    # or if request.GET.get("q")
    # or if request.GET['q']
    errors = []
    if 'q' in request.GET:
        q = request.GET['q']
        if not q:
            errors.append('Enter a search term.')
        elif len(q) > 20:
            errors.append('Please enter at most 20 characters.')
        else:
            books = Book.objects.filter(title__icontains=q)
            return render(request, 'search_results.html', {'books':books, 'query':q})

    return render(request, 'search_form.html', {'errors':errors})


def year_archive(request, year=2003):
    year = year
    context = {
        "year":year
    }
    return render(request, 'year_archive.html', context)

mysite/mysite/views.py
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.shortcuts import render
from .forms import ContactForm
from django.core.mail import send_mail
import datetime


def hello(request):
    #host = request.is_secure()
    # host = request.get_full_path()
    # host = request.get_host()
    # host = request.path

    # try:
    #     ua = request.META['HTTP_USER_AGENT']
    # except KeyError:
    #     ua = 'Unknown'

    # withou try: except catch
    ua = request.META.get('HTTP_USER_AGENT', 'Unknown')

    return HttpResponse("Welcome to the page at %s <br/> and Your user agent is %s" % (request.path, ua))


def display_meta(request):
    values = request.META.items()
    values=sorted(values)
    html = []
    for k, v in values:
        html.append('<tr><td>%s</td><td>%s</td></tr>' % (k, v))
    return HttpResponse('<table>%s</table>' % '\n'.join(html))


def current_datetime(request):
    now = datetime.datetime.now()
    return render(request,
                'current_datetime.html',
                {
                    'title': 'Current datetime',
                    'current_date':now.date(),
                    'current_time': now.time(),
                })


def hours_ahead(request, offset):
    try:
        offset = int(offset)
    except ValueError:
        raise Http404
    dt = datetime.datetime.now() + datetime.timedelta(hours=offset)
    #assert False
    html = "In %s hour(s), it will be %s." % (offset, dt)
    return HttpResponse(html)


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            send_mail(
                cd['subject'],
                cd['message'],
                cd.get('email', 'noreplay@example.com'),
                ['abdulhalim.cu10@gmail.com'],
            )
            return HttpResponseRedirect('/contact/')
    else:
        form = ContactForm()
    return render(request, 'contact_form.html', {'form':form})



def debug(request):
    return HttpResponse("DEBUG is True")

mysite/books/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock title%} | books</title>
</head>
<body>
    <div>
        {% block content %}

        {% endblock content %}
    </div>
</body>
</html>

mysite/books/templates/books/publisher_list.html
{% extends "base.html" %}
{% block title %} Publishers {% endblock title %}
{% block content %}
    <h2>Publishers</h2>
    <ul>
        {% for publisher in object_list %}
            <li>{{ publisher.name }}</li>
        {% endfor %}
    </ul>
{% endblock %}

mysite/books/templates/current_datetime.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
    Current date: {{ current_date }} <br/>
    Current time: {{ current_time }}
</body>
</html>

mysite/books/templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h3>Welcome to Books apps</h3>
</body>
</html>

mysite/books/templates/search_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Search</title>
</head>
<body>
    <h3>Search FORM</h3>
    <div>
    {% if errors %}
        {% for error in errors %}
            <p style="color: red;">{{ error }}</p>
        {% endfor %}
    {% endif %}
    </div>

    <form action="/search/" method="get">
        <input type="text" name="q">
        <input type="submit" name="Search">
    </form>

</body>
</html>

mysite/books/templates/search_results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Book Search</title>
</head>
<body>
    <h2>You searched for: <strong>{{ query }}</strong></h2>

    {% if books %}
    <div>
        <p>Found {{books|length }} book{{ books|pluralize}}</p>
        <ul>
            {% for book in books %}
            <li>{{ book.title }}</li>
            {% endfor %}
        </ul>
    </div>
    {% else %}
        <p>No matched your search criteria.</p>
    {% endif %}
</body>
</html>

mysite/books/templates/year_archive.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Year-archive</title>
</head>
<body>
    <h2>Year Archive</h2>
    <p>Selected Year is {{ year }}</p>
</body>
</html>

mysite/templates/contact_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>contact form</title>

    <style type="text/css">
        ul.errorlist {
            margin: 0;
            padding:0;
        }
        .errorlist li {
            background-color: red;
            color: #FFFFFF;
            display: block;
            font-size: 10px;
            margin: 0 0 3px;
            padding: 4px 5px;
        }
    </style>

</head>
<body>
    <h2>Contact Us</h2>

    <div>
        {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{form.errors|pluralize}} below.
        </p>
        {% endif %}

        <form action="" method="post">
            <div class="field">
                {{ form.subject.errors }}
                <label for="id_subject">Subject:</label>
                {{ form.subject }}
            </div>
            <div class="field">
                {{ form.email.errors }}
                <label for="id_email">E-mail:</label>
                {{ form.email }}
            </div>
            <div class="field">
                {{ form.message.errors }}
                <label for="id_message">Message:</label>
                {{ form.message }}
                <!--<div class="field{% if form.message.errors %} errors{% endif %}">-->
                    <!--{% if form.message.errors %}-->
                        <!--<ul>-->
                        <!--{% for error in form.message.errors %}-->
                            <!--<li><strong>{{ error }}</strong></li>-->
                        <!--{% endfor %}-->
                        <!--</ul>-->
                    <!--{% endif %}-->
                    <!--<label for="id_message">Message:</label>-->
                    <!--{{ form.message }}-->
                <!--</div>-->
            </div>
            {% csrf_token %}
            <input type="submit" value="Submit" />
        </form>
    </div>
</body>
</html>

mysite/templates/current_datetime.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
    Current date: {{ current_date }} <br/>
    Current time: {{ current_time }}
</body>
</html>